/**
 * @file Fluid.h
 */
#pragma once

#include <string>
#include <vector>
#include "Channel.h"
#include "Edge.h"

namespace sim {

/**
 * @brief Class to define the fluid parameters of a droplet or the continuous phase.
 */
class Fluid {
  private:
    int const id;                     ///< Unique identifier of the fluid.
    std::string name = "";            ///< Name of the fluid.
    std::vector<Fluid*> mixedFluids;  ///< List of previous fluids, if this fluid was generated by mixing.
    int mixtureId;                    ///< Id of mixture that consists of 100% of this fluid.
    double viscosity;                 ///< Dynamic viscosity of the fluid in Pas.
    double density;                   ///< Density of the fluid in kg/m^3.
    double concentration;             ///< Concentration of the fluid in % (between 0.0 and 1.0).
    double molecularSize;             ///< Molecular size in m^3.
    double diffusionCoefficient;      ///< Diffusion coefficient of the fluid in m^2/s
    double saturation;                ///< Saturation value to translate the concentration in an actual concentration value [mol/m^3]

  public:
    /**
     * @brief Constructs a fluid.
     * @param[in] id Unique identifier of the fluid.
     * @param[in] viscosity Viscosity of the fluid in Pas.
     * @param[in] density Density of the fluid in kg/m^3.
     * @param[in] concentration Concentration of the fluid in % (between 0.0 and 1.0).
     * @param[in] molecularSize Molecular size in m^3.
     * @param[in] diffusionCoefficient Diffusion coefficient of the fluid in m^2/s.
     * @param[in] saturation Saturation value to translate the concentration in an actual concentration value [mol/m^3].
     * @param[in] mixtureId Id of the mixture that consists to 100% of this fluid.
     */
    Fluid(int id, double viscosity, double density, double concentration, double molecularSize, double diffusionCoefficient, double saturation, int mixtureId);

    /**
     * @brief Set name of fluid.
     * @param[in] name Name of the fluid.
     */
    void setName(std::string name);

    /**
     * @brief Retrieve the unique identifier of the fluid.
     * @return Unique identifier of the fluid.
     */
    int getId() const;

    /**
     * @brief Retrieve name of the fluid.
     * @return The name of the fluid.
     */
    std::string getName() const;

    /**
     * @brief Retrieve viscosity of the fluid.
     * @return The viscosity of the fluid in Pas.
     */
    double getViscosity() const;

    /**
     * @brief Retrieve density of the fluid.
     * @return Density of the fluid in kg/m^3.
     */
    double getDensity() const;

    /**
     * @brief Retrieve concentration of the fluid.
     * @return Concentration of the fluid in % (between 0.0 and 1.0).
     */
    double getConcentration() const;

    /**
     * @brief Retrieve the molecular size of the fluid.
     * 
     * @return Molecular diameter in m. 
     */
    double getMolecularSize() const;

    /**
     * @brief Get the diffusion coefficient of the fluid.
     * 
     * @return Diffusion coefficient of the fluid in m^2/s.
     */
    double getDiffusionCoefficient() const;

    /**
     * @brief Get the saturation of a fluid
     * 
     * @return Saturation value to translate the concentration in an actual concentration value [mol/m^3].
     */
    double getSaturation() const;

    /**
     * @brief Get the mixture id of the mixture that only consists of this fluid.
     * 
     * @return Id of the mixture that only consists of this fluid.
     */
    int getMixtureId() const;

    /**
     * @brief Adds a fluid from which the current fluid was created by mixing.
     * @param fluid Pointer to fluid.
     */
    void addMixedFluid(Fluid* fluid);

    /**
     * @brief Gets the list of fluids, that created the actual fluid due to mixing.
     * @return List of mixed fluids.
     */
    const std::vector<Fluid*>& getMixedFluids() const;
};

}  // namespace sim