name: 🍎 • CI

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**/*.h'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ 'main' ]
    paths:
      - '**/*.h'
      - '**/*.cpp'
      - '**/*.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos.yml'
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: 🍎 macos-26 with clang++
    runs-on: macos-26

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Remove existing 2to3 binary
      - name: Remove existing 2to3 binary
        run: sudo rm /usr/local/bin/2to3 || true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: "macos-26-clang++-Release"
          variant: ccache
          save: true
          max-size: 10G

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build_release

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build_release
        run: >
          cmake ${{github.workspace}}
          -DCMAKE_CXX_COMPILER=clang++
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_POLICY_VERSION_MINIMUM=3.5

      - name: Build
        working-directory: ${{github.workspace}}/build_release
        run: cmake --build . --config Release -j4 # all macOS runners provide at least 3 cores

      - name: Test
        working-directory: ${{github.workspace}}/build_release
        run: ./dropletTest
